# Filebeat DaemonSet - 日志采集
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: springcloud-alibaba
  labels:
    app: filebeat
    component: logging
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
        component: logging
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.12.0
          args: [
            "-c", "/etc/filebeat.yml",
            "-e",
          ]
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "elasticsearch-service:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: password
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
            privileged: true
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
            - name: data
              mountPath: /usr/share/filebeat/data
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: app-logs
              mountPath: /app/logs
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: filebeat-config
        - name: data
          hostPath:
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
            type: Directory
        - name: varlog
          hostPath:
            path: /var/log
            type: Directory
        - name: app-logs
          hostPath:
            path: /var/log/app-logs
            type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: springcloud-alibaba
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
      # 采集应用日志
      - type: log
        enabled: true
        paths:
          - /app/logs/*.log
          - /var/log/app-logs/**/*.log
        fields:
          app: springcloud-alibaba
          env: production
        fields_under_root: true
        multiline:
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
          negate: true
          match: after

      # 采集容器日志
      - type: container
        enabled: true
        paths:
          - /var/lib/docker/containers/*/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
                - logs_path:
                    logs_path: "/var/lib/docker/containers/"

    # 输出到 Elasticsearch
    output.elasticsearch:
      hosts: ["${ELASTICSEARCH_HOSTS}"]
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      indices:
        - index: "springcloud-alibaba-%{+yyyy.MM.dd}"
          when.equals:
            app: "springcloud-alibaba"
        - index: "kubernetes-%{+yyyy.MM.dd}"
          when.equals:
            kubernetes.container.name: "filebeat"

    # 日志模板
    setup.template.name: "springcloud-alibaba"
    setup.template.pattern: "springcloud-alibaba-*"
    setup.template.settings:
      index.number_of_shards: 3
      index.number_of_replicas: 1

    # Kibana 配置
    setup.kibana:
      host: "kibana-service:5601"

    # 日志级别
    logging.level: info
    logging.to_files: true
    logging.files:
      path: /var/log/filebeat
      name: filebeat
      keepfiles: 7
      permissions: 0644
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: springcloud-alibaba
  labels:
    app: filebeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    app: filebeat
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - nodes
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filebeat
  labels:
    app: filebeat
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: filebeat
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: springcloud-alibaba
